- hosts: jmeter-master
  gather_facts: False
  tasks:


    - name: create jmx directory
      file:
        path=/usr/local/apache-jmeter-3.0/jmx
        state=directory
        mode=0777


    - local_action: shell  ls -1 /home/administrator/CSV/{{ vnum }}/*
      register: contents


    - name: copy csv files to remote servers
      copy:
         src="{{ item }}"
         dest=/usr/local/apache-jmeter-3.0/jmx/
         owner=root
         group=root
         mode=0777
      with_items: contents.stdout_lines
