---
    - ec2_remote_facts:
        filters:
          instance-state-name: running
          "tag:Name": "{{ ec2_term_Tag_Name }}"
          "tag:Type": "{{ ec2_term_tag_Type }}"
          "tag:Environment": "{{ ec2_tag_Environment }}"
        region: "{{ ec2_term_region }}"
      register: ec2_info



    - name: Terminate Jmeter Instances
      ec2:
        state: 'absent'
        instance_ids: "{{ item.id }}"
        region: "{{ item.region }}"
      with_items: ec2_info.instances
